### ISSUE TITLE
No Data on Grafana

### ISSUE THREAD

**Issue by Aw3s0m3T3rry** [greenstatic/bigbluebutton-exporter#103]
Hi,

I have installed bbb-exporter as a service on one of our BBB servers and the All in one monitoring stack on another server.  Were setting it up like this because we want to monitor multiple BBB servers. 

When viewing /metrics I am able to view the metrics of output of the bbb-exporter. 
But Grafana shows "No Data" on all dashboards. When changing datasources I sometimes get this error as well:
```
Templating
Template variables could not be initialized: undefined
```

I think I missed a step somewhere. Your help would be appreciated.

Docker-compose.yaml:
```
version: '3.2'
services:
  bbb-exporter:
    container_name: bbb-exporter
    image: greenstatic/bigbluebutton-exporter:v0.6.0
    network_mode: host
    #volumes:
      # Can be removed if `RECORDINGS_METRICS_READ_FROM_DISK` is set to false (or omitted).
      # See https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations for details.
      #- "/var/bigbluebutton:/var/bigbluebutton:ro"
    environment:
      BIND_IP: "127.0.0.1"
#      RECORDINGS_METRICS_READ_FROM_DISK: "false"
    env_file:
      - bbb_exporter_secrets.env
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.20.0
    network_mode: host
    command:
      # Default commands from Dockerfile
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # Our custom commands - metrics will be stored for 400 days
      - "--storage.tsdb.retention.time=400d"
      - "--web.listen-address=127.0.0.1:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.1
    network_mode: host
    environment:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
      GF_SERVER_HTTP_PORT: "3001"
      GF_SERVER_ROOT_URL: "https://example.com/monitoring"
    volumes:
      - "grafana_data:/var/lib/grafana"
    restart: unless-stopped

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.0.1
    network_mode: host
    command:
      - "--path.rootfs=/host"
      - "--web.listen-address=127.0.0.1:9100"
    pid: "host"
    volumes:
      - type: "bind"
        source: "/"
        target: "/host"
        read_only: true
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
```
  
Prometheus.yaml

```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bbb'
    relabel_configs:
      - source_labels: ['__address__']
        separator:     ':'
        regex:         '(.*):.*'
        target_label:  'instance'
        replacement:   '$1'
    static_configs:
      - targets: ['localhost:9688']

- job_name: 'bbb_node_exporter'
    metrics_path: '/metrics/'
    params:
      format: [prometheus]
    honor_labels: true
    scheme: http
    basic_auth:
      username: "username"  # TODO - change
      password: "password"  # TODO - change
    static_configs:
    # TODO - change, add all of your BigBlueButton exporter hosts
- targets: ['example.com']
```

![image](https://user-images.githubusercontent.com/49946255/139449873-0c8d45a8-93e7-4582-9648-df5e0f48c2b8.png)
