### ISSUE TITLE
Prometheus error scraping BBB v.2.6

### ISSUE THREAD

**Issue by diokast** [greenstatic/bigbluebutton-exporter#120]
We are using bbb-exporter for the past 3 years for several BBB servers (v2.4) and everything is fine. 
Recently, we created some new BBB servers with v.2.6 and we followed the same procedure to install (docker) bbb-exporter (https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/#docker-installation-recommended).
The docker-compose.yaml is:
```
version: '3'
services:
  bbb-exporter:
    container_name: "bbb-exporter"
    image: greenstatic/bigbluebutton-exporter:v0.6.1
    ports:
      - "127.0.0.1:9688:9688"
    volumes:
      # Can be removed if `RECORDINGS_METRICS_READ_FROM_DISK` is set to false (or omitted).
      # See https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations for details.
      - "/var/bigbluebutton:/var/bigbluebutton:ro"
    # There can be an issue of DNS resolution if the hostname and the api url is the same. 
    # Docker then advertises the FQDN as a local 127.0.0.1 IP inside the container.
    extra_hosts: 
    #  - 'host-fqdn:PUBLIC.HOST.IP.ADDRESS'
      - 'bbb3.ourdomain.ltd:XXX.XXX.XXX.XXX'  # example
    environment:
      RECORDINGS_METRICS_READ_FROM_DISK: "true"
    env_file:
      - secrets.env
    restart: unless-stopped
```
and the prometheus.yml:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'bbb-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'bbb'
    scrape_interval: 5s
    metrics_path: '/metrics'
    scheme: https
    basic_auth:
      username: OURUSERNAME
      password: OURPASS
    static_configs:
    - targets: ['bbb3.ourdomain.ltd', 'bbb4.ourdomain.ltd', 'bbb5.ourdomain.ltd', 'bbb6.ourdomain.ltd', 'bbb7.ourdomain.ltd']

```
All BBB v2.4.x can be scraped from Prometheus normally except the new ones v.2.6. We get an error 
`Get "http://bbb3.ourdomain.ltd:82/metrics/": context deadline exceeded`

The confusing matter is that bbb_node_exporter (https://bigbluebutton-exporter.greenstatic.dev/installation/node_exporter/#step-by-step-guide) is scraped normally without error for all BBB servers.

Seems like something not working right with new http2 nginx config in v.2.6. The BBB server insatllation was made according the official documentation and there no custom configurations.
Any suggestions for a workaround will be appreciated.
Thanks in advance

**Comment by greenstatic** [comment]
Just to be clear; [node exporter](https://github.com/prometheus/node_exporter) is a separate process (and project), from the bbb_exporter. It's in the documentation just because you often wish to also monitor the node the bbb server is running on and not just bbb related metrics (i.e. bbb_exporter).

Regarding the `context deadline exceeded` error that seems fishy, since that is a Go HTTP library related error. bbb_exporter is implemented in Python which leads me to suspect that you have a Nginx config issue.

Are you sure that `http://bbb3.ourdomain.ltd:82/metrics/` is directed to the bbb_exporter server (`127.0.0.1:9688/`) - https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/#6-add-nginx-site-configuration ?

**Comment by diokast** [comment]
Thanks for quick response.
We followed as usual the addition of monitoring.nginx like below:
```
# BigBlueButton Exporter (metrics)
location /metrics/ {
    auth_basic "BigBlueButton Exporter";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_pass http://127.0.0.1:9688/;
    include proxy_params;
}
```
Prometheus Endpoint is https://bbb3.ourdomain.ltd/metrics. The problem is around the new nginx config v2.6. in /etc/nginx/sites-available/bigbluebutton.

```
....
server {
  # this double listenting is intended. We terminate SSL on haproxy. HTTP2 is a
  # binary protocol. haproxy has to decide which protocol is spoken. This is
  # negotiated by ALPN.
  #
  # Depending on the ALPN value traffic is redirected to either port 82 (HTTP2,
  # ALPN value h2) or 81 (HTTP 1.0 or HTTP 1.1, ALPN value http/1.1 or no value)

  listen 127.0.0.1:82 http2 proxy_protocol;
  listen [::1]:82 http2;
  listen 127.0.0.1:81 proxy_protocol;
  listen [::1]:81;
  server_name bbb3.apopsi.gr;

    
    # HSTS (comment out to enable)
    #add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  access_log  /var/log/nginx/bigbluebutton.access.log;

  # BigBlueButton landing page.
  location / {
    root   /var/www/bigbluebutton-default/assets;
    try_files $uri @bbb-fe;
  }

  # Include specific rules for record and playback
  include /etc/bigbluebutton/nginx/*.nginx;
}
....


```

I did a test and copy-pasted the link https://bbb3.ourdomain.ltd/metrics in a browser. After some seconds the URL becomes https://bbb3.ourdomain.ltd:82/metrics. Next, I edited the URL (deleted the :82) direct in address bar and hit Enter. Now bbb-exports answered normally. You can try yourself with the real URL https://bbb3.apopsi.gr/metrics

**Comment by diokast** [comment]
Hi, I just figured what caused the bad redirection. In prometheus job is now needed a trailing slash on the path declarion:
```
  - job_name: 'bbb'
    scrape_interval: 5s
    metrics_path: '/metrics/'
    scheme: https
    basic_auth:
    ...
```
That was really weird, because without the trailing slash (/metrics) is fine working for BBB prior of v2.6. I think is the combination of haproxy and nginx reverse proxy redirects.
Thanks again for your support.
