### ISSUE TITLE
Grafana Dashboard Queries

### ISSUE THREAD

**Issue by niaz151** [greenstatic/bigbluebutton-exporter#5]
When I attempt to use the Prometheus data source in Grafana I'm getting 'No Data' on all the graphs. If I attempt to query Prometheus with the same queries specified in the Grafana graphs I get no results back. Is there any insight you can offer to this?

Example:  
BBB-API Graph Query: bbb_api_up{instance="$instance"}
Searching the same query in Prometheus does not return a result even though Prometheus has Netdata setup as a target

**Comment by greenstatic** [comment]
what about if you remove the filter, i.e. try the query: `bbb_api_up`?

**Comment by greenstatic** [comment]
`bbb_api_up` is the metrics that this (bigbluebutton) exporter exposes, which you then scrape using Prometheus. Can you also see if you have any metrics from Netdata, e.g. try query `netdata_system_load_load_average`. If none of these two queries return a value, either you are not communicating with Prometheus correctly or you have a broken Prometheus setup.

Try the two queries on Prometheus (`localhost:9090/graph`), if they both return values it means that you have a working Prometheus setup except did not configure Grafana correctly to communicate with Prometheus. If you do not get any results, you need to look at your Prometheus config.

**Comment by niaz151** [comment]
Thank you for getting back to me. The `bbb_api_up` does not return a value , however, the `netdata_system_load_load_average`  does return values. What could potentially be causing this?

**Comment by greenstatic** [comment]
It seems like you have not configured the bigbluebutton-exporter correctly. I suggest you double check that you included the correct `API_SECRET` and `API_BASE_URL` (make sure there is a trailing slash, like so: `https://example.com/bigbluebutton/api/`). 

Then check your docker logs; `sudo docker logs -f <container_name>`, if you used the supplied docker-compose.yml file, the container_name should be: `bbb-exporter`.

**Comment by niaz151** [comment]
The endpoint exposed via bbb-conf --secret is  `https:<my-url>/bigbluebutton` . Should I change the endpoint in my secrets.env file such that the endpoint is `https:<my-url>/bigbluebutton/api/` ?

Upon running `docker logs -f bbb-exporter` with the `/bigbluebutton/api` endpoint I get the following log output: 
```
2020-04-03 21:02:38,500 [INFO]: HTTP server started on port: 9688
2020-04-03 21:02:38,500 [INFO]: Collecting metrics from BigBlueButton API
2020-04-03 21:02:38,677 [INFO]: Finished collecting metrics from BigBlueButton API
```

**Comment by greenstatic** [comment]
> The endpoint exposed via bbb-conf --secret is `https:<my-url>/bigbluebutton` . Should I change the endpoint in my secrets.env file such that the endpoint is `https:<my-url>/bigbluebutton/api/` ?
> 
> Upon running `docker logs -f bbb-exporter` with the `/bigbluebutton/api` endpoint I get the following log output:
> 
> ```
> 2020-04-03 21:02:38,500 [INFO]: HTTP server started on port: 9688
> 2020-04-03 21:02:38,500 [INFO]: Collecting metrics from BigBlueButton API
> 2020-04-03 21:02:38,677 [INFO]: Finished collecting metrics from BigBlueButton API
> ```

Yes, the main endpoint for bbb is `https:<my-url>/bigbluebutton`, but the API endpoint bbb exposes is `https:<my-url>/bigbluebutton/api/`. Try that and report back :)

**Comment by niaz151** [comment]
The logs from the previous message were from using the `https:<my-url>/bigbluebutton/api/ `endpoint.

**Comment by greenstatic** [comment]
Can you try the `bbb_api_up` query now in Prometheus?

**Comment by niaz151** [comment]
You can a screenshot of the output below. 
![Capture](https://user-images.githubusercontent.com/24725512/78408455-2a840380-75d5-11ea-85e0-54cd3e5979ae.PNG)

**Comment by greenstatic** [comment]
Can you also share the Prometheus config?

**Comment by niaz151** [comment]
# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'netdata-scrape'

    metrics_path: 'netdata/api/v1/allmetrics'
    params:
      # format: prometheus | prometheus_all_hosts
      # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP
      format: [prometheus]
      #
      # sources: as-collected | raw | average | sum | volume
      # default is: average
      #source: [as-collected]
      #
      # server name for this prometheus - the default is the client IP
      # for Netdata to uniquely identify it
      #server: ['prometheus1']
    honor_labels: true
    scheme: https
    static_configs:
      - targets: ['kt5.ktlearning.com:19999']

**Comment by niaz151** [comment]
I apologize for the bad formatting, I just copy and pasted.

**Comment by greenstatic** [comment]
Can you edit your comment and surround your YAML with three backticks (`) - See this for more details: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by niaz151** [comment]
It's been updated, thank you for the info.

**Comment by greenstatic** [comment]
You do not have a scrape config entry for bigbluebutton-exporter. See the [instructions](https://github.com/greenstatic/bigbluebutton-exporter#installation) step 8 for an example.

I strongly recommend you setup HTTP basic auth for your endpoint (bigbluebutton-exporter and netdata), the linked instructions also cover how to do that.

I also see you have the scrape config for Prometheus set to `0.0.0.0`, I hope you are not running Prometheus exposed on a public IP address. Prometheus does not have any authentication and your Prometheus installation will be vulnerable.

**Comment by greenstatic** [comment]
After adding bbb-exporter to the scrape config do not forget to restart Prometheus, so the updated config will be used.

**Comment by niaz151** [comment]
I've edited the yaml file to the following:

``` 
# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'netdata-scrape'

    metrics_path: 'netdata/api/v1/allmetrics'
    params:
      # format: prometheus | prometheus_all_hosts
      # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP
      format: [prometheus]
      #
      # sources: as-collected | raw | average | sum | volume
      # default is: average
      #source: [as-collected]
      #
      # server name for this prometheus - the default is the client IP
      # for Netdata to uniquely identify it
      #server: ['prometheus1']
    honor_labels: true
    scheme: https
    basic_auth:
        username: <my_username>
        password: <my_password>
    static_configs:
      - targets: ['kt5.ktlearning.com:19999']

    - job_name: 'bbb'
      scrape_interval: 5s
      scheme:https
      basic_auth:
        username: <my_username>
        password: <my_password>
      static_configs:
         - targets: ['kt5.ktlearning.com']
```

I then ran ```sudo systemctl stop prometheus``` as well as ```sudo systemctl start prometheus``` . Let me know if anything else is needed as I'm still not getting any query data back.
