### ISSUE TITLE
wrong metrics_path in documentation

### ISSUE THREAD

**Issue by hex-m** [greenstatic/bigbluebutton-exporter#70]
following the [intallation manual](https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/) and trying to add multiple BigBlueButton Servers does not work.

The [example configuration](https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/#configuration-steps) has a wrong value in the filed `metrics_path` and the `job_name` is confusing too.

current example config
```
- job_name: 'bbb_node_exporter'
    metrics_path: '/node_exporter/metrics'
    params:
      format: [prometheus]
    honor_labels: true
    scheme: https
    basic_auth:
      username: <HTTP BASIC AUTH USERNAME>  # TODO - change
      password: <HTTP BASIC AUTH PASSWORD>  # TODO - change
    static_configs:
    # TODO - change, add all of your BigBlueButton exporter hosts
    - targets: ['bbb.example.com', 'bbb2.example.com', 'bbb3.example.com']
```

suggested config for multiple bbb-servers
```
- job_name: 'bbb'
  scheme: https
  basic_auth:
    username: "<HTTP BASIC AUTH USERNAME>"
    password: "<HTTP BASIC AUTH PASSWORD>"
  static_configs:
  - targets: ['bbb1.example.com', 'bbb2.example.com']
```
