### ISSUE TITLE
Grafana problem

### ISSUE THREAD

**Issue by HouseDwarf** [greenstatic/bigbluebutton-exporter#93]
Hi.

I have a problem with my All-In-One-Monitoring stack.

I followed the instructions on **https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/** and I also read **https://github.com/greenstatic/bigbluebutton-exporter/issues/19**

Following the instructions at https://bigbluebuttonexporter.greenstatic.dev/installation/all_in_one_monitoring_stack/#6-setup-grafana I am stuck at step 6.

I get this error message when I try to connect to bbb.xyz.tld/bigbluebutton/monitoring/

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Apr 21 09:44:01 CEST 2021
There was an unexpected error (type=Not Found, status=404).
No message available
```

My prometheus.yaml (and the other files following) looks like this and resides in /root/bbb-monitoring/ 

```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bbb'
    relabel_configs:
      - source_labels: ['__address__']
        separator:     ':'
        regex:         '(.*):.*'
        target_label:  'instance'
        replacement:   '$1'
    static_configs:
      - targets: ['localhost:9688']

  - job_name: 'bbb_node_exporter'
    params:
      format: [prometheus]
    honor_labels: true
    relabel_configs:
      - source_labels: ['__address__']
        separator:     ':'
        regex:         '(.*):.*'
        target_label:  'instance'
        replacement:   '$1'
    static_configs:
      - targets: ['localhost:9100']

```
My bbb_exporter_secrets.env looks like this

```
API_BASE_URL=bbb.xyz.tld/bigbluebutton/api/
API_SECRET=p8WLOUA4TIUOJt2AH5J2tujrWCr52mnXWGMOo2Zg9F
```

My docker-compose.yaml looks like this

```
version: '3.2'
services:
  bbb-exporter:
    container_name: bbb-exporter
    image: greenstatic/bigbluebutton-exporter:v0.6.0
    network_mode: host
    volumes:
      # Can be removed if `RECORDINGS_METRICS_READ_FROM_DISK` is set to false (or omitted).
      # See https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations for details.
      - "/var/bigbluebutton:/var/bigbluebutton:ro"
    environment:
      BIND_IP: "127.0.0.1"
      RECORDINGS_METRICS_READ_FROM_DISK: "true"
    env_file:
      - bbb_exporter_secrets.env
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.20.0
    network_mode: host
    command:
      # Default commands from Dockerfile
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # Our custom commands - metrics will be stored for 400 days
      - "--storage.tsdb.retention.time=400d"
      - "--web.listen-address=127.0.0.1:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.1
    network_mode: host
    environment:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
      GF_SERVER_HTTP_PORT: "3001"
      GF_SERVER_ROOT_URL: "https://bbb.xyz.tld/bigbluebutton/monitoring/"
    volumes:
      - "grafana_data:/var/lib/grafana"
    restart: unless-stopped

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.0.1
    network_mode: host
    command:
      - "--path.rootfs=/host"
      - "--web.listen-address=127.0.0.1:9100"
    pid: "host"
    volumes:
      - type: "bind"
        source: "/"
        target: "/host"
        read_only: true
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
```
